name: Tests
on:
  push:
    branches: [main, stable]
    paths-ignore: ['docs/**', '*.md', '*.rst']
  pull_request:
    paths-ignore: [ 'docs/**', '*.md', '*.rst' ]
jobs:
  tests:
    name: ${{ matrix.name || matrix.python }}
    runs-on: ${{ matrix.os || 'ubuntu-latest' }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - {python: '3.13'}
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - run: pip install numpy
    - run: pip install pytest

    - run: pytest