name: Tests
on:
  push:
    branches: [main, stable]
    paths-ignore: ['docs/**', '*.md', '*.rst']
  pull_request:
    paths-ignore: [ 'docs/**', '*.md', '*.rst' ]
jobs:
  tests:
    name: ${{ matrix.name || matrix.python }}
    runs-on: ${{ matrix.os || 'ubuntu-latest' }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - {python: '3.13'}
          - {python: '3.12'}
          - {name: Windows, python: '3.12', os: windows-latest}
          - {name: Mac, python: '3.12', os: macos-latest}
          - {python: '3.11'}
          - {python: '3.10'}
          - {python: '3.9'}
          - {name: PyPy, python: 'pypy-3.10', tox: pypy310}
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: install specklesnake
      run: |
      pip install numpy
      pip install pytest

    - name: run tests
      run: pytest